### PR TITLE
Fixes a bug where not all of the similar types gets returned.

### PR DESCRIPTION
**Pull request by eidheim**
You can merge this right away

### CODE REVIEW

**Comment by zalox** [comment]
I don't like the removal of line breaks in the function signatures. I think only src/Tokens.cc should be commited. Maybe also the file_path refactor.

**Comment by eidheim** [comment]
I have trouble reading the multiline functions when looking over lots of source code, but its just a personal preference. If you want, you can merge it and change it back. I do not have access to a computer for a few days

**Comment by zalox** [comment]
Well I quess I have the same argument. It's personal preference, however when we wrote the initial code our styleguide said no lines over 80 chars.

**Comment by eidheim** [comment]
Thats from the old days when coding in a text terminal with fixed char width. When writing in juci this makes no sense;)

**Pull request merged**
